connect the CREATE_BOOK and REMOVE_BOOK actions with the React component
tGodson/react-redux-app pull request #3
Opened 2020-12-13 16:10 UTC by tGodson

- Make the BooksForm component stateful
- Connect the REMOVE_BOOK action to the component

2020-12-13 17:07 UTC, wathigo requested changes
### Changes Required :heavy_multiplication_x:
Great job on this milestone.
Let's make a few changes before we move on.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-12-13 17:07 UTC, wathigo commented on src/components/Book.js
> +);
**REQUIRED**
* It accepts `handleRemoveBook` prop.
* It adds Remove book button to the book row [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/RemoveBookButton.png) from path right
* It attaches passed handleRemoveBook to on click event of Remove book button

2020-12-14 05:04 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @tGodson, great job on this project :+1: Excellent job fixing all the comments outlined by the previous TSE :smile: Awesome :+1: 

[OPTIONAL]
- Kindly follow the Gitflow/Github flow. Where the pull request is created from the `feature` branch to the `development` branch
- Kindly add a live link version of this project. For example; Heroku deploy
Kindly merge to development :fireworks: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-12-14 05:04 UTC, addod19 commented on src/containers/BookList.js
> +function BooksList({ books, removeBook }) {
[OPTIONAL]
- Let us use ES6 classes. `const BookList = ({ books, removeBook }) => {}` instead of `function BookList =  ({ books, removeBook }) {}`

2020-12-15 12:53 UTC, closed without merging